package com.boldust.gui.entities;
// Generated May 17, 2014 9:11:55 PM by Hibernate Tools 3.6.0



/**
 * A generated by hbm2java
 */
public class A  implements java.io.Serializable {


     private int a;

    public A() {
    }

    public A(int a) {
       this.a = a;
    }
   
    public int getA() {
        return this.a;
    }
    
    public void setA(int a) {
        this.a = a;
    }




}


